/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * logging.java
 *
 * Created on Jan 13, 2012, 11:44:25 AM
 */

package traffic_alerts;

import de.javasoft.plaf.synthetica.SyntheticaBlackMoonLookAndFeel;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.jdesktop.application.Action;
import de.javasoft.plaf.synthetica.SyntheticaBlackMoonLookAndFeel;

/**
 *
 * @author Prasan
 */
public class logging extends javax.swing.JFrame {

    /** Creates new form logging */
    public logging() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Traffic Alerts");
        setBounds(new java.awt.Rectangle(480, 200, 0, 0));
        setMinimumSize(new java.awt.Dimension(400, 350));
        setName("Form\n"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18));
        jLabel1.setText(" ULTIMATE TRAFFIC ALERT SYSTEM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 330, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("User Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText(" Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jTextField1.setFont(new java.awt.Font("Serif", 1, 10));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 200, -1));

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 10));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 200, -1));

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(logging.class, this);
        jButton1.setAction(actionMap.get("login")); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login1.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton1KeyReleased(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 170, 90));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel1.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 120, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login2.png")));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
         jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login1.png")));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel2.png")));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel1.png")));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        try {

            if (evt.getKeyCode() == 10) {

                login();

            }
        } catch (SQLException ex) {
            Logger.getLogger(logging.class.getName()).log(Level.SEVERE, null, ex);
    }//GEN-LAST:event_jButton1KeyPressed
    }



        private void jButton1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyReleased
            // TODO add your handling code here:
            try {

            if (evt.getKeyCode() == 10) {


 login();
            }
        } catch (SQLException ex) {
            Logger.getLogger(logging.class.getName()).log(Level.SEVERE, null, ex);
        }
        }//GEN-LAST:event_jButton1KeyReleased

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        }//GEN-LAST:event_jButton1ActionPerformed

         private void enterKey(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        if(evt.KEY_TYPED ==evt.VK_ENTER){
            try {
                System.out.println("msdnjdsvjvnjvn");
                login();
            } catch (SQLException ex) {
                Logger.getLogger(logging.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

         private void keyre(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            try {
              login();
            } catch (SQLException ex) {
                Logger.getLogger(logging.class.getName()).log(Level.SEVERE, null, ex);
            }}
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {

         try {

			//UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                        UIManager.setLookAndFeel(new SyntheticaBlackMoonLookAndFeel());

			} catch (Exception evt) {}

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new logging().setVisible(true);
            }
        });
    }

    @Action
    public void login() throws SQLException {
        Connection con = DBConnector.getMyConnection();
        Statement stm = con.createStatement();
        java.sql.ResultSet rst = stm.executeQuery("select* from user where name = '" + jTextField1.getText() + "' && password = '" + jPasswordField1.getText() + "'");

        if (rst.next()) {
            mainSystem ms = new mainSystem();
            ms.setVisible(true);
            this.setVisible(false);

            jTextField1.setText("");
            jPasswordField1.setText(null);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Invalid username and password. ");
            jPasswordField1.setText("");
            

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
