/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * routMap.java
 *
 * Created on Jul 1, 2012, 12:36:10 PM
 */

package traffic_alerts;

import de.javasoft.plaf.synthetica.SyntheticaBlackMoonLookAndFeel;
import javax.swing.UIManager;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Prasan
 */
public class routMap extends javax.swing.JFrame {

    /** Creates new form routMap */
    public routMap() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbStart = new javax.swing.JComboBox();
        cmbEnd = new javax.swing.JComboBox();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();

        setTitle("Traffic Solutions");
        setBounds(new java.awt.Rectangle(290, 40, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setText("START POSITION");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("END POSITION");
        jLabel2.setName("jLabel2"); // NOI18N

        cmbStart.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "katubedda", "rathmalana", "mt.lavinia", "dehiwala", "wallawatte", "bambalapitiya", "kollpitiya", "pettah", "fort", " " }));
        cmbStart.setName("cmbStart"); // NOI18N

        cmbEnd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "katubedda", "rathmalana", "mt.lavinia", "dehiwala", "wallawatte", "bambalapitiya", "kollpitiya", "pettah", "fort" }));
        cmbEnd.setName("cmbEnd"); // NOI18N
        cmbEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEndActionPerformed(evt);
            }
        });

        jProgressBar1.setName("jProgressBar1"); // NOI18N
        jProgressBar1.setStringPainted(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 120));

        jPanel2.setName("jPanel2"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ALTERNATIVE ROUT", "AVG SPEED (kmph)", "COST", "CONDITION"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 550, 110));

        jPanel3.setName("jPanel3"); // NOI18N

        jInternalFrame1.setName("jInternalFrame1"); // NOI18N
        jInternalFrame1.setVisible(true);
        jInternalFrame1.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrame1InternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrame1InternalFrameOpened(evt);
            }
        });
        jInternalFrame1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jInternalFrame1ComponentAdded(evt);
            }
        });
        jInternalFrame1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jInternalFrame1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 794, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 810, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEndActionPerformed
        jProgressBar1.setValue(100);

        String locationNo1;
        String locationNo2;
        String start;
        String end;
        locationNo1 = cmbStart.getSelectedItem().toString();
        start = locationNo1;
        locationNo2 = cmbEnd.getSelectedItem().toString();
        end = locationNo2;
        // TODO add your handling code here:
        try {
            

            System.out.println(locationNo1);
            System.out.println(start);
            System.out.println(locationNo2);

            String query = "SELECT * FROM routmap WHERE location1 = '"+locationNo1+"' AND location2 = '"+locationNo2+"'";
            Connection conn = DBConnector.getMyConnection();
            ResultSet rs1 = conn.createStatement().executeQuery(query);
            System.out.println(rs1.next());
            DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
            while(dt.getRowCount()>0){
               dt.removeRow(0);
               }
            while(rs1.next()){
                Vector v = new Vector();
                v.add(rs1.getString("name"));
                v.add(rs1.getString("avgspeed"));
                v.add(rs1.getString("cost"));
                v.add(rs1.getString("condition"));

                dt.addRow(v);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        if(start=="katubedda"&&end=="rathmalana"){
         try {
        XYSeriesCollection dataset = new XYSeriesCollection();
        XYSeries series1 = new XYSeries("Main Rout");
        series1.add(80.234, 10.239);
        series1.add(80.456, 13.678);
        series1.add(80.623, 14.876);
        series1.add(80.745, 15.765);
        series1.add(81.345, 20.879);
        series1.add(81.123, 21.896);
        series1.add(81.567, 22.789);
        series1.add(82.091, 24.908);
        XYSeries series2 = new XYSeries("Alternative Rout 1");
        series2.add(80.234, 10.239);
        series2.add(80.362, 12.538);
        series2.add(80.456, 13.678);
        final XYSeries series3 = new XYSeries("Alternative Rout 2");
        series3.add(80.234, 10.239);
        series3.add(80.371, 11.538);
        series3.add(80.456, 13.678);
        dataset.addSeries(series1);
        dataset.addSeries(series2);
        dataset.addSeries(series3);
        JFreeChart chart = ChartFactory.createXYLineChart("Traffic Solutions", "Longitude", "Latitude", dataset, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel chartPanel = new ChartPanel(chart);
        jInternalFrame1.setContentPane(chartPanel);
       } catch (Exception e) {
       }
        
        }
        else if(start=="rathmalana"&&end=="mt.lavinia"){
            try {
                XYSeriesCollection dataset = new XYSeriesCollection();
        XYSeries series1 = new XYSeries("Main Rout");
        series1.add(80.234, 10.239);
        series1.add(80.456, 13.678);
        series1.add(80.623, 14.876);
        series1.add(80.745, 15.765);
        series1.add(81.345, 20.879);
        series1.add(81.123, 21.896);
        series1.add(81.567, 22.789);
        series1.add(82.091, 24.908);
        XYSeries series2 = new XYSeries("Alternative Rout 1");
        series2.add(80.456, 13.678);
        series2.add(80.562, 12.738);
        series2.add(80.623, 14.876);
        final XYSeries series3 = new XYSeries("Alternative Rout 2");
        series3.add(80.456, 13.678);
        series3.add(80.562, 15.538);
        series3.add(80.623, 14.876);
        dataset.addSeries(series1);
        dataset.addSeries(series2);
        dataset.addSeries(series3);
        JFreeChart chart = ChartFactory.createXYLineChart("Traffic Solutions", "Longitude", "Latitude", dataset, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel chartPanel = new ChartPanel(chart);
        jInternalFrame1.setContentPane(chartPanel);
            } catch (Exception e) {
            }

 }
        else if(start=="mt.lavinia"&&end=="dehiwala"){
            try {
                XYSeriesCollection dataset = new XYSeriesCollection();
        XYSeries series1 = new XYSeries("Main Rout");
        series1.add(80.234, 10.239);
        series1.add(80.456, 13.678);
        series1.add(80.623, 14.876);
        series1.add(80.745, 15.765);
        series1.add(81.345, 20.879);
        series1.add(81.123, 21.896);
        series1.add(81.567, 22.789);
        series1.add(82.091, 24.908);
        XYSeries series2 = new XYSeries("Alternative Rout 1");
        series2.add(80.623, 14.876);
        series2.add(80.730, 17.538);
        series2.add(80.745, 15.765);
        final XYSeries series3 = new XYSeries("Alternative Rout 2");
        series3.add(80.623, 14.876);
        series3.add(80.691, 16.138);
        series3.add(80.745, 15.765);
        dataset.addSeries(series1);
        dataset.addSeries(series2);
        dataset.addSeries(series3);
        JFreeChart chart = ChartFactory.createXYLineChart("Traffic Solutions", "Longitude", "Latitude", dataset, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel chartPanel = new ChartPanel(chart);
        jInternalFrame1.setContentPane(chartPanel);
            } catch (Exception e) {
            }

 }
        else if(start=="dehiwala"&&end=="wallawatte"){
            try {
                XYSeriesCollection dataset = new XYSeriesCollection();
        XYSeries series1 = new XYSeries("Main Rout");
        series1.add(80.234, 10.239);
        series1.add(80.456, 13.678);
        series1.add(80.623, 14.876);
        series1.add(80.745, 15.765);
        series1.add(81.345, 20.879);
        series1.add(81.123, 21.896);
        series1.add(81.567, 22.789);
        series1.add(82.091, 24.908);
        XYSeries series2 = new XYSeries("Alternative Rout");
        series2.add(80.745, 15.765);
        series2.add(80.930, 16.538);
        series2.add(81.345, 20.879);
        dataset.addSeries(series1);
        dataset.addSeries(series2);
        JFreeChart chart = ChartFactory.createXYLineChart("Traffic Solutions", "Longitude", "Latitude", dataset, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel chartPanel = new ChartPanel(chart);
        jInternalFrame1.setContentPane(chartPanel);
            } catch (Exception e) {
            }

 }
         else if(start=="wallawatte"&&end=="bambalapitiya"){
            try {
                XYSeriesCollection dataset = new XYSeriesCollection();
        XYSeries series1 = new XYSeries("Main Rout");
        series1.add(80.234, 10.239);
        series1.add(80.456, 13.678);
        series1.add(80.623, 14.876);
        series1.add(80.745, 15.765);
        series1.add(81.345, 20.879);
        series1.add(81.123, 21.896);
        series1.add(81.567, 22.789);
        series1.add(82.091, 24.908);
        XYSeries series2 = new XYSeries("Alternative Rout 1");
        series2.add(81.123, 21.896);
        series2.add(81.123, 22.896);
        series2.add(81.345, 22.879);
        series2.add(81.345, 20.879);
        final XYSeries series3 = new XYSeries("Alternative Rout 2");
        series3.add(81.345, 20.879);
        series3.add(81.291, 18.138);
        series3.add(81.123, 21.896);
        dataset.addSeries(series1);
        dataset.addSeries(series2);
        dataset.addSeries(series3);
        JFreeChart chart = ChartFactory.createXYLineChart("Traffic Solutions", "Longitude", "Latitude", dataset, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel chartPanel = new ChartPanel(chart);
        jInternalFrame1.setContentPane(chartPanel);
            } catch (Exception e) {
            }

 }
        else if(start=="bambalapitiya"&&end=="kollpitiya"){
            try {
                XYSeriesCollection dataset = new XYSeriesCollection();
        XYSeries series1 = new XYSeries("Main Rout");
        series1.add(80.234, 10.239);
        series1.add(80.456, 13.678);
        series1.add(80.623, 14.876);
        series1.add(80.745, 15.765);
        series1.add(81.345, 20.879);
        series1.add(81.123, 21.896);
        series1.add(81.567, 22.789);
        series1.add(82.091, 24.908);
        XYSeries series2 = new XYSeries("Alternative Rout");
        series2.add(81.123, 21.896);
        series2.add(81.123, 22.896);
        series2.add(81.567, 23.879);
        series2.add(81.567, 22.789);
        dataset.addSeries(series1);
        dataset.addSeries(series2);
        JFreeChart chart = ChartFactory.createXYLineChart("Traffic Solutions", "Longitude", "Latitude", dataset, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel chartPanel = new ChartPanel(chart);
        jInternalFrame1.setContentPane(chartPanel);
            } catch (Exception e) {
            }

 }
        else if(start=="kollpitiya"&&end=="pettah"){
            try {
                XYSeriesCollection dataset = new XYSeriesCollection();
        XYSeries series1 = new XYSeries("Main Rout");
        series1.add(80.234, 10.239);
        series1.add(80.456, 13.678);
        series1.add(80.623, 14.876);
        series1.add(80.745, 15.765);
        series1.add(81.345, 20.879);
        series1.add(81.123, 21.896);
        series1.add(81.567, 22.789);
        series1.add(82.091, 24.908);
        XYSeries series2 = new XYSeries("Alternative Rout");
        series2.add(81.567, 22.789);
        series2.add(81.936, 22.579);
        series2.add(82.091, 24.908);
        dataset.addSeries(series1);
        dataset.addSeries(series2);
        JFreeChart chart = ChartFactory.createXYLineChart("Traffic Solutions", "Longitude", "Latitude", dataset, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel chartPanel = new ChartPanel(chart);
        jInternalFrame1.setContentPane(chartPanel);
            } catch (Exception e) {
            }

 }
        else if(start=="katubedda"&&end=="mt.lavinia"){
            try {
                XYSeriesCollection dataset = new XYSeriesCollection();
        XYSeries series1 = new XYSeries("Main Rout");
        series1.add(80.234, 10.239);
        series1.add(80.456, 13.678);
        series1.add(80.623, 14.876);
        series1.add(80.745, 15.765);
        series1.add(81.345, 20.879);
        series1.add(81.123, 21.896);
        series1.add(81.567, 22.789);
        series1.add(82.091, 24.908);
        XYSeries series2 = new XYSeries("Alternative Rout");
        series2.add(80.234, 10.239);
        series2.add(80.523, 16.896);
        series2.add(80.623, 14.876);
        dataset.addSeries(series1);
        dataset.addSeries(series2);
        JFreeChart chart = ChartFactory.createXYLineChart("Traffic Solutions", "Longitude", "Latitude", dataset, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel chartPanel = new ChartPanel(chart);
        jInternalFrame1.setContentPane(chartPanel);
            } catch (Exception e) {
            }

 }
        else if(start=="rathmalana"&&end=="dehiwala"){
            try {
                XYSeriesCollection dataset = new XYSeriesCollection();
        XYSeries series1 = new XYSeries("Main Rout");
        series1.add(80.234, 10.239);
        series1.add(80.456, 13.678);
        series1.add(80.623, 14.876);
        series1.add(80.745, 15.765);
        series1.add(81.345, 20.879);
        series1.add(81.123, 21.896);
        series1.add(81.567, 22.789);
        series1.add(82.091, 24.908);
        XYSeries series2 = new XYSeries("Alternative Rout");
        series2.add(80.456, 13.678);
        series2.add(80.523, 17.896);
        series2.add(80.745, 15.765);
        dataset.addSeries(series1);
        dataset.addSeries(series2);
        JFreeChart chart = ChartFactory.createXYLineChart("Traffic Solutions", "Longitude", "Latitude", dataset, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel chartPanel = new ChartPanel(chart);
        jInternalFrame1.setContentPane(chartPanel);
            } catch (Exception e) {
            }

 }
        else if(start=="mt.lavinia"&&end=="wallawatte"){
            try {
                XYSeriesCollection dataset = new XYSeriesCollection();
        XYSeries series1 = new XYSeries("Main Rout");
        series1.add(80.234, 10.239);
        series1.add(80.456, 13.678);
        series1.add(80.623, 14.876);
        series1.add(80.745, 15.765);
        series1.add(81.345, 20.879);
        series1.add(81.123, 21.896);
        series1.add(81.567, 22.789);
        series1.add(82.091, 24.908);
        XYSeries series2 = new XYSeries("Alternative Rout");
        series2.add(80.623, 14.876);
        series2.add(81.123, 15.896);
        series2.add(81.345, 20.879);
        dataset.addSeries(series1);
        dataset.addSeries(series2);
        JFreeChart chart = ChartFactory.createXYLineChart("Traffic Solutions", "Longitude", "Latitude", dataset, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel chartPanel = new ChartPanel(chart);
        jInternalFrame1.setContentPane(chartPanel);
            } catch (Exception e) {
            }

 }
        else if(start=="wallawatte"&&end=="kollpitiya"){
            try {
                XYSeriesCollection dataset = new XYSeriesCollection();
        XYSeries series1 = new XYSeries("Main Rout");
        series1.add(80.234, 10.239);
        series1.add(80.456, 13.678);
        series1.add(80.623, 14.876);
        series1.add(80.745, 15.765);
        series1.add(81.345, 20.879);
        series1.add(81.123, 21.896);
        series1.add(81.567, 22.789);
        series1.add(82.091, 24.908);
        XYSeries series2 = new XYSeries("Alternative Rout");
        series2.add(81.345, 20.879);
        series2.add(81.423, 18.296);
        series2.add(81.567, 22.789);
        dataset.addSeries(series1);
        dataset.addSeries(series2);
        JFreeChart chart = ChartFactory.createXYLineChart("Traffic Solutions", "Longitude", "Latitude", dataset, PlotOrientation.VERTICAL, true, true, false);
        ChartPanel chartPanel = new ChartPanel(chart);
        jInternalFrame1.setContentPane(chartPanel);
            } catch (Exception e) {
            }

 }
    }//GEN-LAST:event_cmbEndActionPerformed

    private void jInternalFrame1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jInternalFrame1AncestorAdded
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jInternalFrame1AncestorAdded

    private void jInternalFrame1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jInternalFrame1ComponentAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jInternalFrame1ComponentAdded

    private void jInternalFrame1InternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrame1InternalFrameActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jInternalFrame1InternalFrameActivated

    private void jInternalFrame1InternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrame1InternalFrameOpened
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jInternalFrame1InternalFrameOpened

    /**
    * @param args the command line arguments
    */
   
    public static void main(String args[]) {

        try {

			//UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                       UIManager.setLookAndFeel(new SyntheticaBlackMoonLookAndFeel());

			} catch (Exception evt) {}
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new routMap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbEnd;
    private javax.swing.JComboBox cmbStart;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
