/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * smsSender.java
 *
 * Created on Jan 14, 2012, 4:22:18 PM
 */

package traffic_alerts;

import javax.swing.UIManager;
import java.util.Enumeration;
import javax.comm.CommPortIdentifier;
import javax.swing.JOptionPane;
import org.smslib.OutboundMessage;
import org.smslib.Service;
import org.smslib.modem.SerialModemGateway;

/**
 *
 * @author Prasan
 */
public class smsSender extends javax.swing.JFrame {

    /** Creates new form smsSender */
    public smsSender() {
        
        initComponents();
         Enumeration portList = CommPortIdentifier.getPortIdentifiers();
         while(portList.hasMoreElements()){
         CommPortIdentifier cp1 = (CommPortIdentifier)portList.nextElement();
             System.out.println(cp1.getName());
             if(cp1.getName().equals("COM4")){
                 try {

                 } catch (Exception e) {
                 }


             }
         }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setTitle("Traffic Solutions");
        setBounds(new java.awt.Rectangle(480, 200, 0, 0));
        setMinimumSize(new java.awt.Dimension(420, 320));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel1.setText("TO");
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 40, -1));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel2.setText("MESSAGE");
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jTextField1.setText("+94");
        jTextField1.setName("jTextField1"); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 190, -1));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 190, 120));

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        jButton1.setText("SEND");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SerialModemGateway gateway = new SerialModemGateway("modem.com1", "COM4", 460800, "Huawei", "");
        gateway.setInbound(true);
        gateway.setOutbound(true);
        gateway.setSmscNumber("+9477000003");
        Service service = Service.getInstance();
        try {
            service.addGateway(gateway);
            service.startService();
            {
                System.out.println("Modem Information");
                System.out.println("Manufacturer: "+ gateway.getManufacturer());
                System.out.println("Model: "+ gateway.getModel());
                System.out.println("Serial No:"+ gateway.getSerialNo());
                System.out.println("SIM IMSI:"+ gateway.getImsi());
                System.out.println("");

            }
            OutboundMessage msg = new OutboundMessage(jTextField1.getText(), jTextArea1.getText());
            service.sendMessage(msg);
            JOptionPane.showConfirmDialog(this, "Sent!");
        } catch (Exception ex) {
        JOptionPane.showConfirmDialog(this, "Not Sent!\n"+ex.getMessage());

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        try {

			UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");

			} catch (Exception evt) {}

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new smsSender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
